---
- hosts: all
  become: yes
  ignore_errors: true
  tasks:
    - name: uptime
      command: uptime
      register: uptime_output
    
    - name: Debug module
      debug:
        msg: "hello from my playbook"

    - name: Debug module
      debug:
          var: uptime_output
