---
- hosts: ws
  become: yes
  become_user: root
  vars_files: 
    - vars.yml
  vars:
    pkg: httpd
  ignore_errors: yes

  tasks:
    - name: install httpd
      yum: 
        name: "{{ pkg }}"
        state: absent
    - name: install wget
      package:
        name: "{{item}}"
        state: present
      loop: "{{package_list}}"
    - name: create groups
      group:
        name: "{{item}}"
        state: present
      loop: "{{group_list}}"
    - name: create users
      user:
        name: "{{item}}"
        state: present
      loop: "{{user_list}}"
    - name: add user to group
      user:
        name: johnny
        group: florida